version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lorabus
      MYSQL_USER: bleximo
      MYSQL_PASSWORD: 12369874
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      # MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
