import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./component/theme/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LoRa Bus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head> */}
        {/* เปลี่ยน Favicon */}
        {/* <link rel="icon" href="/images/logoHam.png" />{" "} */}
        {/* หรือเปลี่ยนเป็น .png หรือ .svg */}
        {/* เพิ่มรูปภาพโลโก้ */}
        {/* <link rel="apple-touch-icon" sizes="180x180" href="/logo.png" />{" "} */}
        {/* รูปแบบโลโก้ */}
      {/* </head> */}
      
      <ThemeProvider>
        <body className={`${inter.className} dark:text-white`}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
